// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: genta/api/http.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Http struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path   string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *Http) Reset() {
	*x = Http{}
	if protoimpl.UnsafeEnabled {
		mi := &file_genta_api_http_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Http) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Http) ProtoMessage() {}

func (x *Http) ProtoReflect() protoreflect.Message {
	mi := &file_genta_api_http_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Http.ProtoReflect.Descriptor instead.
func (*Http) Descriptor() ([]byte, []int) {
	return file_genta_api_http_proto_rawDescGZIP(), []int{0}
}

func (x *Http) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Http) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var file_genta_api_http_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*Http)(nil),
		Field:         50000,
		Name:          "genta.api.http",
		Tag:           "bytes,50000,opt,name=http",
		Filename:      "genta/api/http.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional genta.api.Http http = 50000;
	E_Http = &file_genta_api_http_proto_extTypes[0]
)

var File_genta_api_http_proto protoreflect.FileDescriptor

var file_genta_api_http_proto_rawDesc = []byte{
	0x0a, 0x14, 0x67, 0x65, 0x6e, 0x74, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x68, 0x74, 0x74, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x65, 0x6e, 0x74, 0x61, 0x2e, 0x61, 0x70,
	0x69, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x32, 0x0a, 0x04, 0x48, 0x74, 0x74, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x3a, 0x45, 0x0a, 0x04, 0x68, 0x74, 0x74, 0x70, 0x12,
	0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18,
	0xd0, 0x86, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x65, 0x6e, 0x74, 0x61, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x52, 0x04, 0x68, 0x74, 0x74, 0x70, 0x42, 0x25,
	0x5a, 0x23, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x65, 0x61,
	0x63, 0x68, 0x33, 0x31, 0x30, 0x2f, 0x67, 0x65, 0x6e, 0x74, 0x61, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_genta_api_http_proto_rawDescOnce sync.Once
	file_genta_api_http_proto_rawDescData = file_genta_api_http_proto_rawDesc
)

func file_genta_api_http_proto_rawDescGZIP() []byte {
	file_genta_api_http_proto_rawDescOnce.Do(func() {
		file_genta_api_http_proto_rawDescData = protoimpl.X.CompressGZIP(file_genta_api_http_proto_rawDescData)
	})
	return file_genta_api_http_proto_rawDescData
}

var file_genta_api_http_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_genta_api_http_proto_goTypes = []interface{}{
	(*Http)(nil),                       // 0: genta.api.Http
	(*descriptorpb.MethodOptions)(nil), // 1: google.protobuf.MethodOptions
}
var file_genta_api_http_proto_depIdxs = []int32{
	1, // 0: genta.api.http:extendee -> google.protobuf.MethodOptions
	0, // 1: genta.api.http:type_name -> genta.api.Http
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_genta_api_http_proto_init() }
func file_genta_api_http_proto_init() {
	if File_genta_api_http_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_genta_api_http_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Http); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_genta_api_http_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_genta_api_http_proto_goTypes,
		DependencyIndexes: file_genta_api_http_proto_depIdxs,
		MessageInfos:      file_genta_api_http_proto_msgTypes,
		ExtensionInfos:    file_genta_api_http_proto_extTypes,
	}.Build()
	File_genta_api_http_proto = out.File
	file_genta_api_http_proto_rawDesc = nil
	file_genta_api_http_proto_goTypes = nil
	file_genta_api_http_proto_depIdxs = nil
}
